import { ILetter } from '../Letters/Letters'

export const lettersPlacedOnBoard: ILetter[] = [
    {
        character: 'w',
        location: 3,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'MAbdvvgDiT',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'e',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '9NzNfRa3ui',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 's',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'u8NTWDBpW8',
        xCoordinate: null,
        yCoordinate: null,
    },
]

export const initialPlayersLetters: ILetter[] = [
    {
        character: 'r',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'PLnBFTcbRu',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'e',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '9NzNfRa3ui',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 's',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'u8NTWDBpW8',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'r',
        location: 2,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'wDKxTkcbvZ',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'e',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'n6gIr7fh9h',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 's',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'H3yx0sEsNO',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'w',
        location: 3,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'MAbdvvgDiT',
        xCoordinate: null,
        yCoordinate: null,
    },
]

export const updatedLetterBag: ILetter[] = [
    {
        character: 'r',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'PLnBFTcbRu',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'r',
        location: 2,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'wDKxTkcbvZ',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'e',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'n6gIr7fh9h',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 's',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'H3yx0sEsNO',
        xCoordinate: null,
        yCoordinate: null,
    },
]

export const recommendedWordLetters: ILetter[] = [
    {
        character: 's',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'u8NTWDBpW8',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'e',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '9NzNfRa3ui',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'w',
        location: 3,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'MAbdvvgDiT',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'e',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'n6gIr7fh9h',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'r',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'PLnBFTcbRu',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 's',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'H3yx0sEsNO',
        xCoordinate: null,
        yCoordinate: null,
    },
]

export const wordLetterPermutations: string[] = [
    'c',
    'cu',
    'cue',
    'ce',
    'ceu',
    'u',
    'uc',
    'uce',
    'ue',
    'uec',
    'e',
    'ec',
    'ecu',
    'eu',
    'euc',
]

export const initialAvailableLetters: ILetter[] = [
    {
        character: 'a',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'yHfPV43zrq',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'b',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'PKbCkyFuYu',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'c',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'FJEruDkQkV',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'd',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '1FL4yhuBJr',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'e',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'kK3XauLl6N',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'f',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'ILC892KrQu',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'g',
        location: 2,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'SMmGbdYVkc',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'h',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'JKszOxqKrF',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'i',
        location: 3,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'cgSeV3c2ZW',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'j',
        location: 3,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'FFRwRl4Y8X',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'k',
        location: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'VcpAkq3sSO',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'l',
        location: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'r5y6RUjM35',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'm',
        location: 0,
        pointValue: 3,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '5bPk6pTnQt',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'n',
        location: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '8VVBjH1ik6',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'o',
        location: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'Gwrna3Ckw4',
        xCoordinate: null,
        yCoordinate: null,
    },
    {
        character: 'p',
        location: 0,
        pointValue: 3,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'vSlTxXluXj',
        xCoordinate: null,
        yCoordinate: null,
    },
]
