export const mockLetterTestData = [
    {
        character: 'a',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'yHfPV43zrq',
    },
    {
        character: 'a',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'ty9395RgMT',
    },
    {
        character: 'a',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '1RfJ15QDXh',
    },
    {
        character: 'a',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'Kllpfkmgpa',
    },
    {
        character: 'a',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'cwwxuXuPlu',
    },
    {
        character: 'a',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'JSHXsU1bj3',
    },
    {
        character: 'a',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '66jiUPHJPN',
    },
    {
        character: 'a',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '91QwufaANZ',
    },
    {
        character: 'a',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'fmi5Wbq4UA',
    },
    {
        character: 'b',
        owner: 0,
        pointValue: 3,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '73fPPLMZ6R',
    },
    {
        character: 'b',
        owner: 0,
        pointValue: 3,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'PKbCkyFuYu',
    },
    {
        character: 'c',
        owner: 0,
        pointValue: 3,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'FJEruDkQkV',
    },
    {
        character: 'c',
        owner: 0,
        pointValue: 3,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '1DifcznXLS',
    },
    {
        character: 'd',
        owner: 0,
        pointValue: 2,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '4vOJbYQBSR',
    },
    {
        character: 'd',
        owner: 0,
        pointValue: 2,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '1FL4yhuBJr',
    },
    {
        character: 'd',
        owner: 0,
        pointValue: 2,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'zpc0n4es4a',
    },
    {
        character: 'd',
        owner: 0,
        pointValue: 2,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'WKwRrMZ1Px',
    },
    {
        character: 'e',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'kK3XauLl6N',
    },
    {
        character: 'e',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'cOgRlyLTsb',
    },
    {
        character: 'e',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'hEC8RSIjh1',
    },
    {
        character: 'e',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'ILC892KrQu',
    },
    {
        character: 'e',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'coHuLanxiS',
    },
    {
        character: 'e',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'LQZRWPPLNI',
    },
    {
        character: 'e',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'SMmGbdYVkc',
    },
    {
        character: 'e',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'X2ORj028r9',
    },
    {
        character: 'e',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'JKszOxqKrF',
    },
    {
        character: 'e',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'OZahUx22NR',
    },
    {
        character: 'e',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'cgSeV3c2ZW',
    },
    {
        character: 'e',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'SPywsvmxhH',
    },
    {
        character: 'f',
        owner: 0,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'uO5ik9P4yz',
    },
    {
        character: 'f',
        owner: 0,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'Mw8SLL7vPm',
    },
    {
        character: 'g',
        owner: 0,
        pointValue: 2,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'FFRwRl4Y8X',
    },
    {
        character: 'g',
        owner: 0,
        pointValue: 2,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'u3ZucsGlhk',
    },
    {
        character: 'g',
        owner: 0,
        pointValue: 2,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'akrfLgEyP7',
    },
    {
        character: 'h',
        owner: 0,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'POOUYZCbHC',
    },
    {
        character: 'h',
        owner: 0,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'rRvikm97uD',
    },
    {
        character: 'i',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'qX1syuVeJP',
    },
    {
        character: 'i',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'byNe7tf0rG',
    },
    {
        character: 'i',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'soCTlF9IQf',
    },
    {
        character: 'i',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'EleZjuUAjd',
    },
    {
        character: 'i',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'gnmaVi4Xa1',
    },
    {
        character: 'i',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'VcpAkq3sSO',
    },
    {
        character: 'i',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'HoPc4Nw7Do',
    },
    {
        character: 'i',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'cMim4lJ9aO',
    },
    {
        character: 'i',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'MQd6oHyw8h',
    },
    {
        character: 'j',
        owner: 0,
        pointValue: 8,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'N64TBq92HJ',
    },
    {
        character: 'k',
        owner: 0,
        pointValue: 5,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'Sg4qfCNlco',
    },
    {
        character: 'l',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'VzprrkhNqu',
    },
    {
        character: 'l',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'r5y6RUjM35',
    },
    {
        character: 'l',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'l5JfM1vhid',
    },
    {
        character: 'l',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '8Fy2i1rYUg',
    },
    {
        character: 'm',
        owner: 0,
        pointValue: 3,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 's6DHsg7qwp',
    },
    {
        character: 'm',
        owner: 0,
        pointValue: 3,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '5bPk6pTnQt',
    },
    {
        character: 'n',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'eQNR2u6Bl5',
    },
    {
        character: 'n',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '8VVBjH1ik6',
    },
    {
        character: 'n',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '6lW7HAwuNI',
    },
    {
        character: 'n',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'KZP699xz9U',
    },
    {
        character: 'n',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'tzCZIrYMBf',
    },
    {
        character: 'n',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'QNzG4hbSYO',
    },
    {
        character: 'o',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'Gwrna3Ckw4',
    },
    {
        character: 'o',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '6i1y7YDIiI',
    },
    {
        character: 'o',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'mnNgPWtSux',
    },
    {
        character: 'o',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'Cf07eONEtn',
    },
    {
        character: 'o',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '8kTVwqge5z',
    },
    {
        character: 'o',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'SY7B8EFHjd',
    },
    {
        character: 'o',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'RDKroljk5k',
    },
    {
        character: 'o',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'r6tEwpQWla',
    },
    {
        character: 'p',
        owner: 0,
        pointValue: 3,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'Uwdwv3ZWMA',
    },
    {
        character: 'p',
        owner: 0,
        pointValue: 3,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'vSlTxXluXj',
    },
    {
        character: 'q',
        owner: 0,
        pointValue: 10,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'XfqI3GtPh9',
    },
    {
        character: 'r',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'OuHA64PVHF',
    },
    {
        character: 'r',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'jVI36XjacD',
    },
    {
        character: 'r',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '0KV37z00YM',
    },
    {
        character: 'r',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'xApAUfM2t9',
    },
    {
        character: 'r',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'wYQGhzBIkx',
    },
    {
        character: 'r',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'fGcMNEhtaD',
    },
    {
        character: 's',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'oPdFuSLUjl',
    },
    {
        character: 's',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'oPyHzrlSkd',
    },
    {
        character: 's',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'PoioofeyXE',
    },
    {
        character: 's',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'XCA8wAj9zG',
    },
    {
        character: 't',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'd1mEupb9t6',
    },
    {
        character: 't',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'yq6CNR7qEd',
    },
    {
        character: 't',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'QnaLZmHqip',
    },
    {
        character: 't',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'MkhuxlZYRw',
    },
    {
        character: 't',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'ppt2n09vcE',
    },
    {
        character: 't',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '4cH9RoFiFG',
    },
    {
        character: 'u',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'hES9ae47sD',
    },
    {
        character: 'u',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '3PYZts9Non',
    },
    {
        character: 'u',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'MYhs0fwFlz',
    },
    {
        character: 'u',
        owner: 0,
        pointValue: 1,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'B9uAeIc9n5',
    },
    {
        character: 'v',
        owner: 0,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'bnN1qnTXfQ',
    },
    {
        character: 'v',
        owner: 0,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'GNgvZiXWxH',
    },
    {
        character: 'w',
        owner: 0,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '7vO8wFHz59',
    },
    {
        character: 'w',
        owner: 0,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'jcBR9Nlo4o',
    },
    {
        character: 'x',
        owner: 0,
        pointValue: 8,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'ZezOjk7nzp',
    },
    {
        character: 'y',
        owner: 0,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'tGVTrEU0rU',
    },
    {
        character: 'y',
        owner: 0,
        pointValue: 4,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'LcBNhzQfGI',
    },
    {
        character: 'z',
        owner: 0,
        pointValue: 10,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'h0iZgPddT0',
    },
    {
        character: ' ',
        owner: 0,
        pointValue: 0,
        turnPlacedOnBoard: null,
        uniqueIdentifier: 'uro6CPFNlf',
    },
    {
        character: ' ',
        owner: 0,
        pointValue: 0,
        turnPlacedOnBoard: null,
        uniqueIdentifier: '75FaHK3bWD',
    },
]
